springdoc:
  swagger-ui:
    path: "swagger-ui"

management:
  server:
    port: 8080


app:
  test: 42
  bot:
    name: "Khakov_Tinkoff_bot"
    token: "5726582564:AAFsSp_JeaLkZL50R03bkgPiGr05428e-EY"
  scrapper:
    url: "localhost"
